# DB \uC811\uC18D \uC815\uBCF4
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengram
    username: root
    password: green502

# MYBATIS \uC0C8\uD305
mybatis:
  mapper-locations: /abc/*.xml

# SWAGGER \uC0C8\uD305
springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8081
